from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .analysis import TouchstoneAnalysis, analyze_touchstone
from .filter_metrics import FilterMetricConfig
from .macro import MacroBuilder
from .runner import ExecutionResult, SonnetRunner
from .specs import AutomationSpec, BoxSpec, UnitsSpec


def _project_path(workspace: Path, save_path: str) -> Path:
    target = Path(save_path)
    if target.is_absolute():
        return target
    return workspace / target


def _prepare_parent(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def _prepare_output_directories(spec: AutomationSpec, workspace: Path) -> None:
    project_path = _project_path(workspace, spec.project.save_path)
    _prepare_parent(project_path)
    for output in spec.output_files:
        parent = Path(output.path).parent
        if str(parent) in {"", "."}:
            continue
        if parent.is_absolute():
            parent.mkdir(parents=True, exist_ok=True)
        else:
            (project_path.parent / parent).mkdir(parents=True, exist_ok=True)


def _resolve_output_path(project_path: Path, raw_path: str) -> Path:
    substituted = raw_path.replace("$BASENAME", project_path.stem)
    target = Path(substituted)
    if target.is_absolute():
        return target
    return project_path.parent / target


def _missing_output_paths(spec: AutomationSpec, project_path: Path) -> list[Path]:
    return [
        output_path
        for output in spec.output_files
        if not (output_path := _resolve_output_path(project_path, output.path)).exists()
    ]


def _apply_units(builder: MacroBuilder, units: UnitsSpec) -> None:
    builder.modify(
        "project",
        Length_unit=units.length,
        Roughness_unit=units.roughness,
        SheetRes_unit=units.sheetres,
        Resistance_unit=units.resistance,
        Inductance_unit=units.inductance,
        Capacitance_unit=units.capacitance,
        Frequency_unit=units.frequency,
        Conductivity_unit=units.conductivity,
        Resistivity_unit=units.resistivity,
    )


def _apply_box(builder: MacroBuilder, box: BoxSpec) -> None:
    builder.modify(
        "project",
        box_size_x=box.size_x,
        box_size_y=box.size_y,
        num_cells_x=box.cells_x,
        num_cells_y=box.cells_y,
    )
    if box.local_origin is not None:
        builder.modify("project", local_origin=box.local_origin)


def build_macro(spec: AutomationSpec) -> MacroBuilder:
    builder = MacroBuilder()
    builder.comment("Generated by auto_sonnet")

    for command in spec.preamble:
        builder.raw(command)

    builder.add_project(alias="project", template=spec.project.template)

    if spec.units is not None:
        _apply_units(builder, spec.units)
    if spec.box is not None:
        _apply_box(builder, spec.box)

    for variable in spec.variables:
        builder.add_variable(alias=variable.key, var_name=variable.name, value=variable.value)
    for dielectric in spec.dielectrics:
        builder.add_dielectric(alias=dielectric.key, name=dielectric.name, eps=dielectric.eps, tan=dielectric.tan)
    for layer in spec.dielectric_layers:
        builder.add_dielectric_layer(alias=layer.key, number=layer.number, thickness=layer.thickness)
        if layer.material_name:
            builder.modify(layer.key, MaterialName=layer.material_name)
    for conductor in spec.conductors:
        builder.add_conductor(alias=conductor.key, name=conductor.name, conductivity=conductor.conductivity)
    for tech_layer in spec.planar_tech_layers:
        builder.add_planar_tech_layer(
            alias=tech_layer.key,
            diel_layer=tech_layer.diel_layer,
            thickness=tech_layer.thickness,
            model_type=tech_layer.model_type,
            material_name=tech_layer.material_name,
            name=tech_layer.name,
        )
    for polygon in spec.polygons:
        builder.add_polygon(alias=polygon.key, tech_layer=polygon.tech_layer, points=polygon.points)
    for port in spec.ports:
        builder.add_port(alias=port.key, port_number=port.port_number, polygon=port.polygon, edge=port.edge)

    for sweep_set in spec.sweep_sets:
        builder.add_sweepset(alias=sweep_set.key)
        for freq_sweep in sweep_set.frequency_sweeps:
            builder.add_freq_sweep(
                alias=freq_sweep.key,
                sweep_set=sweep_set.key,
                sweep_type=freq_sweep.sweep_type,
                start=freq_sweep.start,
                stop=freq_sweep.stop,
                step=freq_sweep.step,
                num_points=freq_sweep.num_points,
                freqs=freq_sweep.freqs,
                freq=freq_sweep.freq,
            )
        for param_sweep in sweep_set.parameter_sweeps:
            builder.add_param_sweep(
                alias=param_sweep.key,
                sweep_set=sweep_set.key,
                variable=param_sweep.variable,
                sweep_type=param_sweep.sweep_type,
                start=param_sweep.start,
                stop=param_sweep.stop,
                step=param_sweep.step,
                num_points=param_sweep.num_points,
                values=param_sweep.values,
                value=param_sweep.value,
                min_value=param_sweep.min_value,
                max_value=param_sweep.max_value,
            )

    for output in spec.output_files:
        builder.add_output_file(
            alias=output.key,
            path=output.path,
            param=output.param,
            file_format=output.file_format,
            format=output.format,
        )

    builder.save(spec.project.save_path)

    for query in spec.project.queries:
        normalized = query.strip().lower()
        if normalized == "num_ports":
            builder.get_num_ports()
        elif normalized == "variables":
            builder.get_variables()
        elif normalized == "optimization":
            builder.get_optimization()
        else:
            builder.raw(query)

    if spec.project.clean_data_before_analyze:
        builder.clean_data()
    if spec.project.verify_before_analyze:
        builder.verify_project()
    if spec.project.analyze:
        builder.analyze(monitor=spec.project.launch_monitor, server=spec.project.server)

    for command in spec.postamble:
        builder.raw(command)
    return builder


@dataclass(slots=True)
class GeneratedArtifacts:
    workspace: Path
    macro_path: Path
    project_path: Path


@dataclass(slots=True)
class RunArtifacts(GeneratedArtifacts):
    execution: ExecutionResult


@dataclass(slots=True)
class RunAndAnalyzeArtifacts:
    run: RunArtifacts
    analysis: TouchstoneAnalysis | None


class SonnetAutomation:
    def __init__(self, runner: SonnetRunner | None = None) -> None:
        self.runner = runner

    def generate(self, spec: AutomationSpec, workspace: str | Path, *, macro_name: str = "sonnet_macro.smc") -> GeneratedArtifacts:
        workspace_path = Path(workspace).resolve()
        workspace_path.mkdir(parents=True, exist_ok=True)
        macro_path = workspace_path / macro_name
        _prepare_output_directories(spec, workspace_path)
        build_macro(spec).write(macro_path)
        return GeneratedArtifacts(
            workspace=workspace_path,
            macro_path=macro_path,
            project_path=_project_path(workspace_path, spec.project.save_path),
        )

    def run(
        self,
        spec: AutomationSpec,
        workspace: str | Path,
        *,
        macro_name: str = "sonnet_macro.smc",
        verbose: bool = False,
        timeout: int | None = None,
    ) -> RunArtifacts:
        artifacts = self.generate(spec, workspace, macro_name=macro_name)
        runner = self.runner or SonnetRunner()
        execution = runner.run_macro(artifacts.macro_path, cwd=artifacts.workspace, verbose=verbose, timeout=timeout)
        if execution.returncode == 0 and spec.project.analyze and spec.output_files:
            missing_outputs = _missing_output_paths(spec, artifacts.project_path)
            if missing_outputs:
                missing_text = "\n".join(str(path) for path in missing_outputs)
                stderr = execution.stderr.rstrip()
                if stderr:
                    stderr += "\n"
                stderr += "Expected output files were not generated:\n" + missing_text
                execution = ExecutionResult(
                    command=execution.command,
                    returncode=1,
                    stdout=execution.stdout,
                    stderr=stderr,
                    cwd=execution.cwd,
                    elapsed_seconds=execution.elapsed_seconds,
                    json_payloads=execution.json_payloads,
                )
        return RunArtifacts(
            workspace=artifacts.workspace,
            macro_path=artifacts.macro_path,
            project_path=artifacts.project_path,
            execution=execution,
        )

    def analyze_touchstone(
        self,
        s2p_path: str | Path,
        *,
        target_path: str | Path | None = None,
        config: FilterMetricConfig | None = None,
        output_path: str | Path | None = None,
    ) -> TouchstoneAnalysis:
        return analyze_touchstone(s2p_path, target_path=target_path, config=config, output_path=output_path)

    def run_and_analyze(
        self,
        spec: AutomationSpec,
        workspace: str | Path,
        *,
        macro_name: str = "sonnet_macro.smc",
        target_path: str | Path | None = None,
        config: FilterMetricConfig | None = None,
        analysis_filename: str | None = "metrics.json",
        verbose: bool = False,
        timeout: int | None = None,
    ) -> RunAndAnalyzeArtifacts:
        run_artifacts = self.run(
            spec,
            workspace,
            macro_name=macro_name,
            verbose=verbose,
            timeout=timeout,
        )
        if run_artifacts.execution.returncode != 0:
            return RunAndAnalyzeArtifacts(run=run_artifacts, analysis=None)

        touchstone_output = next(
            (
                _resolve_output_path(run_artifacts.project_path, output.path)
                for output in spec.output_files
                if _resolve_output_path(run_artifacts.project_path, output.path).suffix.lower() == ".s2p"
            ),
            None,
        )
        if touchstone_output is None or not touchstone_output.exists():
            return RunAndAnalyzeArtifacts(run=run_artifacts, analysis=None)

        analysis_path = None if analysis_filename is None else run_artifacts.project_path.parent / analysis_filename
        analysis = analyze_touchstone(
            touchstone_output,
            target_path=target_path,
            config=config,
            output_path=analysis_path,
        )
        return RunAndAnalyzeArtifacts(run=run_artifacts, analysis=analysis)
